"use strict";
const STORE="gym-tracker-pwa-v1";
const DEFAULT_PLAN=[
 {name:"Push · Chest & Triceps",exercises:[['Barbell Bench Press','3','8-10'],['Incline Dumbbell Press','3','10-12'],['Cable Fly','3','12-15'],['Triceps Pushdown','3','10-12']]},
 {name:"Pull · Back & Biceps",exercises:[['Lat Pulldown','3','8-12'],['Seated Cable Row','3','10-12'],['Face Pull','3','12-15'],['Dumbbell Curl','3','10-12']]},
 {name:"Legs · Lower Body",exercises:[['Barbell Squat','3','6-10'],['Romanian Deadlift','3','8-10'],['Leg Press','3','10-12'],['Calf Raise','3','12-15']]},
 {name:"Upper · Strength",exercises:[['Overhead Press','3','6-10'],['Pull Up','3','6-10'],['Dumbbell Row','3','8-12'],['Lateral Raise','3','12-15']]},
 {name:"Full Body · Conditioning",exercises:[['Goblet Squat','3','10-12'],['Push Up','3','10-15'],['Kettlebell Swing','3','12-15'],['Plank','3','30-60 sec']]}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const dateKey=(d=new Date())=>{const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)};
const prettyDate=key=>new Date(`${key}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'});
const load=()=>{try{return JSON.parse(localStorage.getItem(STORE))||{plan:DEFAULT_PLAN,workouts:[],draft:null}}catch{return {plan:DEFAULT_PLAN,workouts:[],draft:null}}};
let state=load(), calendarDate=new Date(), activeDayIndex=null, timerId=null, timerSeconds=90;
const save=()=>localStorage.setItem(STORE,JSON.stringify(state));
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('show'),2800)}
function dayIndexForToday(){return activeDayIndex===null?(new Date().getDay()+6)%state.plan.length:activeDayIndex}
function todayPlan(){return state.plan[dayIndexForToday()]}
function draft(){const key=dateKey(); if(!state.draft||state.draft.date!==key||state.draft.planIndex!==dayIndexForToday()) state.draft={date:key,planIndex:dayIndexForToday(),exercises:todayPlan().exercises.map(([name,sets,targetReps])=>({name,sets:Number(sets),targetReps,reps:'',weight:'',notes:'',done:false}))};return state.draft}
function calcStreak(){const days=[...new Set(state.workouts.map(w=>w.date))].sort().reverse();let current=0, cursor=new Date();if(!days.includes(dateKey(cursor))) cursor.setDate(cursor.getDate()-1);while(days.includes(dateKey(cursor))){current++;cursor.setDate(cursor.getDate()-1)}let best=0,run=0,last=null;[...days].reverse().forEach(k=>{const d=new Date(`${k}T12:00:00`);if(last&&Math.round((d-last)/86400000)===1)run++;else run=1;best=Math.max(best,run);last=d});return {current,best}}
function allEntries(){return state.workouts.flatMap(w=>w.exercises.filter(e=>e.done&&Number(e.weight)>0).map(e=>({...e,date:w.date,workout:w.name}))) }
function records(){const result={};allEntries().forEach(e=>{const weight=Number(e.weight),oneRM=weight*(1+Math.max(0,(Number(e.reps)||1)-1)/30);if(!result[e.name]||weight>result[e.name].weight||weight===result[e.name].weight&&oneRM>result[e.name].oneRM)result[e.name]={...e,weight,oneRM}});return result}
function renderToday(){const p=todayPlan(),d=draft(), done=d.exercises.filter(e=>e.done).length;$('#todayTitle').textContent=p.name;$('#todayDate').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});$('#exerciseList').innerHTML=d.exercises.map((e,i)=>`<article class="exercise-card ${e.done?'done':''}"><div class="exercise-top"><input aria-label="Complete ${e.name}" class="check" type="checkbox" data-complete="${i}" ${e.done?'checked':''}><div><div class="exercise-name">${e.name}</div><div class="exercise-meta">${e.sets} sets · ${e.targetReps||e.reps||'—'} reps</div></div><button class="ghost timer" data-timer="${i}">⏱ Rest</button></div><div class="inputs"><input data-field="weight" data-index="${i}" type="number" inputmode="decimal" min="0" step="0.5" placeholder="Weight (kg)" value="${e.weight}"><input data-field="reps" data-index="${i}" type="number" inputmode="numeric" min="1" placeholder="Reps achieved" value="${e.reps}"><textarea data-field="notes" data-index="${i}" placeholder="Notes (optional)">${e.notes||''}</textarea></div></article>`).join('');$('#progressBar').style.width=`${d.exercises.length?done/d.exercises.length*100:0}%`;$('#progressText').textContent=`${done} of ${d.exercises.length} exercises complete`;$('#finishWorkout').disabled=done===0;}
function saveInput(e){const index=Number(e.target.dataset.index),field=e.target.dataset.field;draft().exercises[index][field]=e.target.value;save();}
function finishWorkout(){const d=draft(), completed=d.exercises.filter(e=>e.done);if(!completed.length)return toast('Complete at least one exercise first.');const existing=state.workouts.findIndex(w=>w.date===d.date);const w={date:d.date,name:todayPlan().name,exercises:d.exercises.map(e=>({...e})),completedAt:new Date().toISOString()};if(existing>=0)state.workouts[existing]=w;else state.workouts.push(w);state.draft=null;activeDayIndex=null;save();renderAll();toast(`Workout saved — ${completed.length} exercises logged!`)}
function renderPlan(){ $('#planList').innerHTML=state.plan.map((p,i)=>`<article class="plan-card" data-plan="${i}"><h3>${p.name}</h3><p>${p.exercises.map(e=>e[0]).join(' · ')}</p></article>`).join('') }
function renderRecords(){const r=Object.values(records()).sort((a,b)=>a.name.localeCompare(b.name));$('#recordList').innerHTML=r.length?r.map(x=>`<article class="record-card"><div><h3>${x.name}</h3><p>${prettyDate(x.date)} · ${x.reps} reps</p></div><strong>${x.weight} kg<small>Est. 1RM ${x.oneRM.toFixed(1)} kg</small></strong></article>`).join(''):'<div class="detail-card">No PRs yet. Finish a workout with a weight to start tracking records.</div>'}
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate(),logged=new Map(state.workouts.map(w=>[w.date,w]));$('#monthLabel').textContent=new Date(y,m,1).toLocaleDateString(undefined,{month:'long',year:'numeric'});let html='';for(let i=0;i<first;i++)html+='<span class="cal-day blank"></span>';for(let day=1;day<=count;day++){const key=dateKey(new Date(y,m,day)),w=logged.get(key),today=key===dateKey();html+=`<button class="cal-day ${w?'completed':''} ${today?'today':''}" data-date="${key}">${day}${w?`<small>${w.exercises.filter(e=>e.done).length} done</small>`:''}</button>`}$('#calendarGrid').innerHTML=html}
function showDay(key){const w=state.workouts.find(x=>x.date===key);$('#dayDetail').innerHTML=w?`<strong>${w.name}</strong><br>${prettyDate(w.date)}<br><span class="subtle">${w.exercises.filter(e=>e.done).map(e=>`${e.name}${e.weight?` — ${e.weight} kg × ${e.reps}`:''}`).join('<br>')}</span>`:'No workout logged on this date.'}
function renderStats(){const total=state.workouts.length,s=calcStreak(),entries=allEntries(),volume=entries.reduce((n,e)=>n+Number(e.weight)*Number(e.reps)*Number(e.sets||1),0),rec=records();$('#totalWorkouts').textContent=total;$('#longestStreak').textContent=s.best;$('#volumeTotal').textContent=Math.round(volume).toLocaleString();$('#prTotal').textContent=Object.keys(rec).length;const names=[...new Set(entries.map(e=>e.name))].sort(),select=$('#chartExercise'),was=select.value;select.innerHTML=names.length?names.map(n=>`<option ${n===was?'selected':''}>${n}</option>`).join(''):'<option>No exercise data</option>';drawChart(select.value)}
function drawChart(name){const points=allEntries().filter(e=>e.name===name).sort((a,b)=>a.date.localeCompare(b.date)).map(e=>({date:e.date,weight:Number(e.weight)}));const canvas=$('#progressChart'),empty=$('#chartEmpty'),ctx=canvas.getContext('2d'),ratio=devicePixelRatio||1,w=canvas.clientWidth*ratio,h=220*ratio;canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);empty.style.display=points.length<2?'block':'none';if(points.length<2)return;const pad=32*ratio,max=Math.max(...points.map(p=>p.weight)),min=Math.min(...points.map(p=>p.weight)),range=max-min||1;ctx.strokeStyle='#383838';ctx.lineWidth=1*ratio;for(let i=0;i<4;i++){let y=pad+(h-2*pad)*i/3;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke()}ctx.strokeStyle='#ff6b6b';ctx.lineWidth=3*ratio;ctx.beginPath();points.forEach((p,i)=>{let x=pad+(w-2*pad)*i/(points.length-1),y=h-pad-(p.weight-min)/range*(h-2*pad);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#e63946';points.forEach((p,i)=>{let x=pad+(w-2*pad)*i/(points.length-1),y=h-pad-(p.weight-min)/range*(h-2*pad);ctx.beginPath();ctx.arc(x,y,4*ratio,0,Math.PI*2);ctx.fill()});ctx.fillStyle='#aaa';ctx.font=`${11*ratio}px sans-serif`;ctx.fillText(`${max} kg`,pad,16*ratio);ctx.fillText(`${min} kg`,pad,h-7*ratio)}
function renderAll(){const s=calcStreak();$('#streakCount').textContent=s.current;renderToday();renderPlan();renderRecords();renderCalendar();renderStats();$('#connection').textContent=navigator.onLine?'Saved locally · ready offline':'Offline mode · saved locally'}
function openTimer(){timerSeconds=90;updateTimer();$('#timerDialog').showModal();if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();clearInterval(timerId);timerId=setInterval(()=>{timerSeconds--;updateTimer();if(timerSeconds<=0){clearInterval(timerId);timerId=null;$('#timerStatus').textContent='Time to lift!';toast('Rest is over — next set!');if(Notification.permission==='granted')new Notification('Gym Tracker',{body:'Rest is over — next set!'});navigator.vibrate?.([140,60,140])}},1000)}
function updateTimer(){const m=Math.max(0,Math.floor(timerSeconds/60)),s=Math.max(0,timerSeconds%60);$('#timerDisplay').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function exportData(){const file=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=`gym-tracker-backup-${dateKey()}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded.')}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-tab]');if(nav){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b===nav));$$('.tab').forEach(t=>t.classList.toggle('active',t.id===nav.dataset.tab));if(nav.dataset.tab==='stats')renderStats();return}const plan=e.target.closest('[data-plan]');if(plan){activeDayIndex=Number(plan.dataset.plan);state.draft=null;save();renderToday();document.querySelector('[data-tab="today"]').click();toast(`Loaded ${todayPlan().name}`);return}const day=e.target.closest('[data-date]');if(day)return showDay(day.dataset.date);if(e.target.closest('[data-timer]'))return openTimer();if(e.target.id==='finishWorkout')return finishWorkout();if(e.target.id==='prevMonth'){calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()}if(e.target.id==='nextMonth'){calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()}if(e.target.id==='resetPlan'){if(confirm('Reset the starter workout plan? Your saved workouts will remain.')){state.plan=DEFAULT_PLAN;state.draft=null;save();renderAll();toast('Plan reset.')}}if(e.target.id==='addTimer'){timerSeconds+=30;updateTimer()}if(e.target.id==='stopTimer'){clearInterval(timerId);timerId=null;$('#timerDialog').close()}if(e.target.id==='exportData')exportData()});
document.addEventListener('change',e=>{if(e.target.matches('[data-complete]')){draft().exercises[Number(e.target.dataset.complete)].done=e.target.checked;save();renderToday()}if(e.target.id==='chartExercise')drawChart(e.target.value)});document.addEventListener('input',e=>{if(e.target.matches('[data-field]'))saveInput(e)});$('#timerDialog').addEventListener('close',()=>clearInterval(timerId));
window.addEventListener('online',renderAll);window.addEventListener('offline',renderAll);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));renderAll();
